meta_product_name: "MeetMyDog"
meta_title: "MeetMyDog - Des balades avec mon chien !"
meta_description: "MeetMyDog c'est super !"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards